[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "8NGX2ja4eSPUjJfjJjwEi1J54JjVR1vWxUdgqSHdPVvP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/melinamejia/solana-wallet/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
